### ISSUE TITLE
Content not associated with a region is not pruned from ISD before deciding if it's empty

### ISSUE THREAD

**Issue by nigelmegitt** [sandflow/imscHRM#19]
Right now, the imsc-hrm-tests dur003-fail passes when it should fail. See also w3c/imsc-hrm-tests#9.

It used to fail in imscHRM because the previous ISD beginning at 2.5s was considered non-empty, and therefore made the available time for the following ISD beginning at 3s be 0.5s. However, that previous ISD only contained content not associated with any region, and should therefore have been pruned. If it had been pruned, then the ISD should have been considered empty, and therefore the ISD beginning at 3s would have had a full 1s to render, and that older variant of the test should have passed instead of failing.

**Comment by palemieux** [comment]
> However, that previous ISD only contained content not associated with any region, and should therefore have been pruned.

Even though it is pruned, so it still generates an ISD, which, because the region background is `showAlways`, triggers a background clear and region paint.
